import { getServerSession } from 'next-auth'
import LoginBtn from './LoginBtn'
import LogoutBtn from './LogoutBtn'
import './globals.css'
import { Inter } from 'next/font/google'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          {/* 조건식 ? 조건식참일때 남길html : 거짓일때 남길html */}
          {
            session ? 
            <span>{session.user.name}<LogoutBtn/></span>: <LoginBtn/>
          }
        </div>
        {children}
        </body>
    </html>
  )
}
